FROM php:7.1.2-apache
RUN docker-php-ext-install mysqli
RUN apt-get update
RUN apt-get install -y libcurl4-openssl-dev pkg-config libssl-dev
RUN apt-get install -y git
RUN git clone https://github.com/mongodb/mongo-php-driver.git
RUN cd mongo-php-driver && git submodule update --init
RUN cd mongo-php-driver && phpize
RUN cd mongo-php-driver && ./configure && make all && make install
RUN echo "extension=mongodb.so" >> /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini
