FROM mongo:latest

# install Python 3
RUN apt-get update && apt-get install -y build-essential python2.7
RUN apt-get install -y python-setuptools
RUN apt-get install -y python-pip
RUN pip install pymongo
EXPOSE 27017
