version: "2.7"
services:
  www:
    build:
      context: ${PWD}
      dockerfile: Dockerfile.www
    image: alexlevashev/sreality-parser-www:1.0
    container_name: www
    ports:
      - "8001:80"
    volumes:
      - /volume1/docker/Sreality/docker/www:/var/www/html/
    networks:
      - default
  py-mongo:
    container_name: mongodb
    build:
      context: ${PWD}
      dockerfile: Dockerfile.mongodb
    image: alexlevashev/sreality-parser-db-py:1.0
    command: --bind_ip_all
    volumes:
      - /volume1/docker/Sreality/docker/db:/data/db
      - /volume1/docker/Sreality/docker/code:/data/code
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - default
volumes:
  persistent:
